services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - RATELIMIT_STORAGE_URL=redis://redis:6379/1
      - DATABASE_URL=postgresql://imageboard:imageboard@db/imageboard
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - C_FORCE_ROOT=false
      - DATABASE_URL=postgresql://imageboard:imageboard@db/imageboard
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=imageboard
      - POSTGRES_PASSWORD=imageboard
      - POSTGRES_DB=imageboard
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:

networks:
  app-network:
    driver: bridge
