version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - DATABASE_URL=postgresql://imageboard:imageboard@db/imageboard
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_FOLDER=uploads
      - MAX_CONTENT_LENGTH=16777216
      - ALLOWED_EXTENSIONS=png,jpg,jpeg,gif,webp,mp4,webm
      - MAX_FILES_PER_POST=4
      - LOG_LEVEL=INFO
      - DEFAULT_LANGUAGE=ru
      - THEME_DEFAULT=light
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./logs:/app/logs
      - ./search_index:/app/search_index
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=imageboard
      - POSTGRES_PASSWORD=imageboard
      - POSTGRES_DB=imageboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://imageboard:imageboard@db/imageboard
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data: 